"""stat

Revision ID: 9192fc7ae57f
Revises: 
Create Date: 2026-04-12 23:42:16.830539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9192fc7ae57f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('telegram_user_id', sa.String(), nullable=True),
    sa.Column('orange_pi_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_orange_pi_id'), 'users', ['orange_pi_id'], unique=True)
    op.create_table('suspicious_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=False),
    sa.Column('src_mac', sa.String(), nullable=False),
    sa.Column('dst_mac', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('ack_flag_number', sa.Float(), nullable=False),
    sa.Column('https', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('header_length', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('tot_sum', sa.Float(), nullable=False),
    sa.Column('time_to_live', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('psh_flag_number', sa.Float(), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('dns', sa.Float(), nullable=False),
    sa.Column('label', sa.Enum('PENDING', 'BENIGN', 'ATTACK', name='packetlabel'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspicious_packets_dst_mac'), 'suspicious_packets', ['dst_mac'], unique=False)
    op.create_index(op.f('ix_suspicious_packets_label'), 'suspicious_packets', ['label'], unique=False)
    op.create_index(op.f('ix_suspicious_packets_src_ip'), 'suspicious_packets', ['src_ip'], unique=False)
    op.create_index(op.f('ix_suspicious_packets_src_mac'), 'suspicious_packets', ['src_mac'], unique=False)
    op.create_index(op.f('ix_suspicious_packets_user_id'), 'suspicious_packets', ['user_id'], unique=False)
    op.create_table('traffic_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_flows', sa.Integer(), nullable=False),
    sa.Column('anomalous_sources', sa.Integer(), nullable=False),
    sa.Column('suspicious_sources', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_start', name='uq_traffic_stats_user_period')
    )
    op.create_index(op.f('ix_traffic_stats_period_start'), 'traffic_stats', ['period_start'], unique=False)
    op.create_index(op.f('ix_traffic_stats_user_id'), 'traffic_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_stats_user_id'), table_name='traffic_stats')
    op.drop_index(op.f('ix_traffic_stats_period_start'), table_name='traffic_stats')
    op.drop_table('traffic_stats')
    op.drop_index(op.f('ix_suspicious_packets_user_id'), table_name='suspicious_packets')
    op.drop_index(op.f('ix_suspicious_packets_src_mac'), table_name='suspicious_packets')
    op.drop_index(op.f('ix_suspicious_packets_src_ip'), table_name='suspicious_packets')
    op.drop_index(op.f('ix_suspicious_packets_label'), table_name='suspicious_packets')
    op.drop_index(op.f('ix_suspicious_packets_dst_mac'), table_name='suspicious_packets')
    op.drop_table('suspicious_packets')
    op.drop_index(op.f('ix_users_orange_pi_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
