"""added to suspicious_packets table some new columns

Revision ID: ce58dc7787de
Revises: 492998b9f71f
Create Date: 2026-02-22 01:35:49.598834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ce58dc7787de'
down_revision: Union[str, Sequence[str], None] = '492998b9f71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    packet_label_enum = sa.Enum('PENDING', 'BENIGN', 'ATTACK', name='packetlabel')
    packet_label_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suspicious_packets', sa.Column('src_ip', sa.String(), nullable=False))
    op.add_column('suspicious_packets', sa.Column('dst_mac', sa.String(), nullable=False))

    op.add_column('suspicious_packets', sa.Column('label', packet_label_enum, nullable=False, server_default='PENDING'))

    op.create_index(op.f('ix_suspicious_packets_dst_mac'), 'suspicious_packets', ['dst_mac'], unique=False)
    op.create_index(op.f('ix_suspicious_packets_label'), 'suspicious_packets', ['label'], unique=False)
    op.create_index(op.f('ix_suspicious_packets_src_ip'), 'suspicious_packets', ['src_ip'], unique=False)
    op.create_index(op.f('ix_suspicious_packets_src_mac'), 'suspicious_packets', ['src_mac'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suspicious_packets_src_mac'), table_name='suspicious_packets')
    op.drop_index(op.f('ix_suspicious_packets_src_ip'), table_name='suspicious_packets')
    op.drop_index(op.f('ix_suspicious_packets_label'), table_name='suspicious_packets')
    op.drop_index(op.f('ix_suspicious_packets_dst_mac'), table_name='suspicious_packets')

    op.drop_column('suspicious_packets', 'label')
    op.drop_column('suspicious_packets', 'dst_mac')
    op.drop_column('suspicious_packets', 'src_ip')
    # ### end Alembic commands ###

    packet_label_enum = sa.Enum('PENDING', 'BENIGN', 'ATTACK', name='packetlabel')
    packet_label_enum.drop(op.get_bind(), checkfirst=True)